// Generated by CoffeeScript 1.7.1
(function() {
  var all_ids, fs;

  fs = require("fs");

  all_ids = function() {
    var f, flist, ids;
    flist = fs.readdirSync("data");
    return ids = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = flist.length; _i < _len; _i++) {
        f = flist[_i];
        _results.push(f.slice(0, -5));
      }
      return _results;
    })();
  };

  exports.all_ids_names = function() {
    var c, id, id_f, ids, name, result, _i, _len;
    ids = all_ids();
    result = [];
    for (_i = 0, _len = ids.length; _i < _len; _i++) {
      id = ids[_i];
      id_f = fs.readFileSync("data/" + id + ".json");
      c = JSON.parse(id_f);
      name = c.name;
      result.push({
        "id": id,
        "name": name
      });
    }
    return result;
  };

  exports.all_ids = all_ids;

  exports.find_regitem_by_id = function(id) {
    var f;
    return f = fs.readFileSync("data/" + id + ".json");
  };

}).call(this);

//# sourceMappingURL=model.map
