// Generated by CoffeeScript 1.7.1
(function() {
  var fs, md;

  fs = require("fs");

  md = require("marked");

  exports.page = function(req, res) {
    var markdown_content, page_name;
    page_name = req.params["name"];
    markdown_content = fs.readFileSync("md_page/" + page_name + ".md", {
      encoding: "utf-8"
    });
    return res.render("md_page", {
      "md": md,
      "markdownContent": markdown_content
    });
  };

  exports.static_page = function(req, res) {
    var content, fn;
    content = fs.readFileSync("md_page/" + req.params["name"] + ".html", {
      encoding: "utf-8"
    });
    fn = function(i) {
      return i;
    };
    return res.render("md_page", {
      "md": fn,
      "markdownContent": content
    });
  };

}).call(this);

//# sourceMappingURL=md_page.map
