// Generated by CoffeeScript 1.7.1
(function() {
  var model;

  model = require("../model");

  exports.regitem = function(req, res) {
    var context, f, f1, flist, reg_id;
    reg_id = req.params["id"];
    console.log(reg_id);
    flist = model.all_ids();
    f1 = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = flist.length; _i < _len; _i++) {
        f = flist[_i];
        if (f === reg_id) {
          _results.push(f);
        }
      }
      return _results;
    })();
    console.log(f1);
    if (f1[0]) {
      context = model.find_regitem_by_id(f1[0]);
      context = JSON.parse(context);
      return res.render("regitem", context);
    } else {
      return res.render("error", {
        "message": "没有找到相应编号的正则表达式!"
      });
    }
  };

  exports.post_regitem = function(req, res) {
    return void 0;
  };

}).call(this);

//# sourceMappingURL=regitem.map
