// Generated by CoffeeScript 1.7.1
(function() {
  var fs;

  fs = require("fs");

  exports.regitem = function(req, res) {
    var context, f, f1, flist, reg_id;
    reg_id = req.params["id"];
    console.log(reg_id);
    flist = fs.readdirSync("data");
    f1 = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = flist.length; _i < _len; _i++) {
        f = flist[_i];
        if (f.slice(0, -5) === reg_id) {
          _results.push(f);
        }
      }
      return _results;
    })();
    console.log(f1);
    if (f1[0]) {
      context = fs.readFileSync("data/" + f1[0]);
      context = JSON.parse(context);
      return res.render("regitem", context);
    } else {
      return res.render("error", {
        "message": "没有找到相应编号的正则表达式!"
      });
    }
  };

  exports.post_regitem = function(req, res) {
    return void 0;
  };

}).call(this);

//# sourceMappingURL=regitem.map
